server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/daraja
      username: develop
      password: Password123
      database: hrms_sample_db

kafka:
  bootstrap-servers: localhost:9092
  group-id: daraja-group
