server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  data:
    mongodb:
      uri: mongodb://develop:Password123@mongodb:27017/daraja

kafka:
  bootstrap-servers: kafka:9092
  group-id: daraja-group
